class Chat {
  final String name, lastMessage, image, time;
  final bool isActive;

  Chat({
    required this.name,
    required this.lastMessage,
    required this.image,
    required this.time,
    required this.isActive,
  });
}

List chatsData = [
  Chat(
    name: "Arvindh",
    lastMessage: "Hope you are doing well...",
    image: "assets/images/user.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Haswanth",
    lastMessage: "Hello Charan! I am...",
    image: "assets/images/user_2.png",
    time: "Now",
    isActive: true,
  ),
  Chat(
    name: "Yash Anna",
    lastMessage: "Do you have update...",
    image: "assets/images/user_3.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Manu",
    lastMessage: "You’re welcome :)",
    image: "assets/images/user_4.png",
    time: "18m",
    isActive: true,
  ),
  Chat(
    name: "Pallavi",
    lastMessage: "Thanks",
    image: "assets/images/user_5.png",
    time: "18m",
    isActive: false,
  ),
  Chat(
    name: "Arvindh",
    lastMessage: "Hope you are doing well...",
    image: "assets/images/user.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Haswanth",
    lastMessage: "Hello Charan! I am...",
    image: "assets/images/user_2.png",
    time: "Now",
    isActive: true,
  ),
  Chat(
    name: "Yash Anna",
    lastMessage: "Do you have update...",
    image: "assets/images/user_3.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Manu",
    lastMessage: "You’re welcome :)",
    image: "assets/images/user_4.png",
    time: "18m",
    isActive: true,
  ),
  Chat(
    name: "Pallavi",
    lastMessage: "Thanks",
    image: "assets/images/user_5.png",
    time: "18m",
    isActive: false,
  ),
  Chat(
    name: "Arvindh",
    lastMessage: "Hope you are doing well...",
    image: "assets/images/user.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Haswanth",
    lastMessage: "Hello Charan! I am...",
    image: "assets/images/user_2.png",
    time: "Now",
    isActive: true,
  ),
  Chat(
    name: "Yash Anna",
    lastMessage: "Do you have update...",
    image: "assets/images/user_3.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Manu",
    lastMessage: "You’re welcome :)",
    image: "assets/images/user_4.png",
    time: "18m",
    isActive: true,
  ),
  Chat(
    name: "Pallavi",
    lastMessage: "Thanks",
    image: "assets/images/user_5.png",
    time: "18m",
    isActive: false,
  ),
  Chat(
    name: "Arvindh",
    lastMessage: "Hope you are doing well...",
    image: "assets/images/user.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Haswanth",
    lastMessage: "Hello Charan! I am...",
    image: "assets/images/user_2.png",
    time: "Now",
    isActive: true,
  ),
  Chat(
    name: "Yash Anna",
    lastMessage: "Do you have update...",
    image: "assets/images/user_3.png",
    time: "Now",
    isActive: false,
  ),
  Chat(
    name: "Manu",
    lastMessage: "You’re welcome :)",
    image: "assets/images/user_4.png",
    time: "18m",
    isActive: true,
  ),
  Chat(
    name: "Pallavi",
    lastMessage: "Thanks",
    image: "assets/images/user_5.png",
    time: "18m",
    isActive: false,
  ),
];
